version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Change if your requirements.txt is in a subfolder
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"