name: Auto Update with Script

on:
  workflow_dispatch:  # You can trigger it manually from the Actions tab
  schedule:
    - cron: "0 6 * * *"  # Daily at 6AM UTC

jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run the file modification script
        run: python3 scripts/modify_readme.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update by GitHub Action" || echo "No changes to commit"
          git push