name: Auto Update with Script

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: "0 6 * * *"  # Daily at 6AM UTC

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run the file modification script
        run: python3 scripts/modify_readme.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-update by GitHub Action"
          git push https://x-access-token:${{ secrets.MY_CUSTOM_TOKEN }}@github.com/thealphakenya/Alphaai.git HEAD:main
